import Hello from "../components/hello";

//overwriting the default metadata for Home page
export const metadata = {
  title: "Home | Next.js",
  description: "Generated by Mark",
};

export default function Home() {
  console.log("Server Component type");

  return (
    <>
      <h1 className="text-3xl">First page</h1>
      <Hello />
    </>
  );
}
